### ISSUE TITLE
.exe built with patch?

### ISSUE THREAD

**Issue by chrisnappi** [russelldavis/DoIt#1]
Do you have a .exe built with this patch?

**Comment by russelldavis** [comment]
I no longer have it around, sorry.

**Comment by chrisnappi** [comment]
Thanks.

**Comment by chrisnappi** [comment]
Managed to do this myself - for anyone else who finds this Git and then looks in the Closed Issues :D This still works great.  

Follow this guide to install VS build tools: https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line  

Then use this command line: 
rc /r doit.rc
cl doit.c doitlib.c listener.c /link doit.res wsock32.lib  user32.lib shell32.lib gdi32.lib

That's it!
